#!/bin/sh
docker stop rabbit
docker rm rabbit
docker run -e mq_ip=172.16.102.122 -e mq_port=8082 -e stomp_ip=172.16.102.124 -e stomp_port=5672 -d --hostname rabbit --name rabbit -p 15674:15674 -p 15672:15672 -p 4369:4369 -p 5671:5671 -p 5672:5672 -p 25672:25672  mshen7310/rabbitmq:latest
last_line=`docker logs --tail 1 rabbit`
while [ $last_line -neq ' completed with 14 plugins.' ]; do
    echo 'waiting'
    sleep 2
done

